Here we will study linear algebra and how NumPy can provide us with all the useful tools we use in linear algebra.
First, we'll demonstrate what vectors look like, and then matrices. Note, column vectors and row vectors have different formats as NumPy arrays.

In [2]:
#importing the goods
import numpy as np
from numpy import linalg as la

In [5]:
#row vectors
x1 = np.array([[1,2,-3]])
x2 = np.array([[0,-3,6]])
#column vectors
y1 = np.array([[1],[-2],[5]])
y2 = np.array([[-2],[5],[0]])
#note the shape difference but same dimension
print(np.shape(x1))
print(np.shape(y1))
print(np.ndim(x1))
print(np.ndim(y1))

(1, 3)
(3, 1)
2
2


We can find the magnitudes of the vectors, take dot products, cross products and other operations we use in linear algebra.

In [27]:
#Vector addition
x3 = x1 + x2
print(x3)
print()
#Scaling a vector
w1 = 2*x1
w2 = 0*y1
print(w1)
print(w2)
print()
#Of course these operations work when joined
y3 = 2*y1-4*y2
print(y3)
print()
#Euclidean norm of a vector
x1n = la.norm(x1)
y3n = la.norm(y3)
print(x1n)
print(y3n)
print()
#Dot product and cross products
print(np.dot(x1,x3.T))
print(np.dot(y1.T,y2))
print()
#Notice the order we have to calculate this in, otherwise we get another operation
#Dot products have to make sense between a vector and a transposed vector.
#Here's what happens if we swap the order.
print(np.dot(x1.T,x3))
print(np.dot(y1,y2.T))
print()
#Cross products only work for row vectors because they're acting as 2 different
#axises of the arrays. Remember these are still arrays which take entries, and
#have axises. Dimensions must be compative even if objects have the same shape.
print(np.cross(x1,x2))
print(np.cross(y1.T,x1))

[[ 1 -1  3]]

[[ 2  4 -6]]
[[0]
 [0]
 [0]]

[[ 10]
 [-24]
 [ 10]]

3.7416573867739413
27.85677655436824

[[-10]]
[[-12]]

[[ 1 -1  3]
 [ 2 -2  6]
 [-3  3 -9]]
[[ -2   5   0]
 [  4 -10   0]
 [-10  25   0]]

[[ 3 -6 -3]]
[[-4  8  4]]


We can have matrix operations on larger arrays of more than one axis and higher dimension.

In [51]:
#Defining matrices
M = np.array([[0,2,1,3],
[3,2,8,1],
[1,0,0,3],
[0,3,2,1]])
#Identity Matrix
I = np.identity(4)
#Determinant
print("M:\n", M)
print("Determinant: %.1f"%la.det(M))
print("I:\n", I)
print("M*I:\n", np.dot(M, I))
print()
#Inverse of a matrix
print('Inv(M):\n',la.inv(M))
print()
#Matrix times inverse is Identity
#The formatting is to remove numbers e-16 which are basically 0
print('M*Inv(M):\n',np.array_str((M@la.inv(M)),precision=1,suppress_small=True))

M:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
Determinant: -38.0
I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
M*I:
 [[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]

Inv(M):
 [[-1.57894737 -0.07894737  1.23684211  1.10526316]
 [-0.63157895 -0.13157895  0.39473684  0.84210526]
 [ 0.68421053  0.18421053 -0.55263158 -0.57894737]
 [ 0.52631579  0.02631579 -0.07894737 -0.36842105]]

M*Inv(M):
 [[ 1.  0.  0.  0.]
 [ 0.  1. -0. -0.]
 [ 0.  0.  1. -0.]
 [ 0.  0.  0.  1.]]


Now that we've seen Python's Linear Algebra package, we can use it in the most practical case. We can solve a system of equations of the normal form $A\bold{x}=\bold{y}$ where $A$ is a square matrix. Otherwise we would have infinite solutions to the system, which aren't of interest. We'll assume $A$ is a matrix with linearly independent columns/rows. Consider $A$ to be a $4 \times 4$ matrix for the following system:
\begin{align*}
-x_4+5x_3+3x_2+2x_1 &= 2\\
3x_4-2x_3-2x_2     &= -3\\
-4x_3+9x_2+2x_1 &= 1\\
6x_4+x_3+x_2-4x_1 &=5 
\end{align*}

In [ ]:
#A matrix
A = np.array([[-1,5,3,2],
              [3,-2,-2,0],
              [0,-4,9,2],
              [6,1,1,-4]])
#Our desired vector
y = np.array([2,-3,1,5])
#our solution
x = la.solve(A,y)
print(x)
